from pathlib import Path
p=Path('src/main.jsx')
s=p.read_text()
s=s.replace("const [user,setUser]=useState(null),[authLoading,setAuthLoading]=useState(true),[facilities,setFacilities]=useState([]),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[loading,setLoading]=useState(true)","const [user,setUser]=useState(null),[authLoading,setAuthLoading]=useState(true),[facilities,setFacilities]=useState([]),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[searchResults,setSearchResults]=useState([]),[reviews,setReviews]=useState([]),[reviewRating,setReviewRating]=useState(5),[reviewNotes,setReviewNotes]=useState(''),[loading,setLoading]=useState(true)")
s=s.replace(".order('name').limit(5000)",".order('name').limit(1500)")
old="const searchResults=useMemo(()=>{const q=norm(query);if(!q)return[];const ts=q.split(' ').filter(Boolean);return facilities.map(f=>{const hay=norm([f.name,f.address,f.city,f.state_code,f.zip].filter(Boolean).join(' '));if(!ts.every(t=>hay.includes(t)))return null;const n=norm(f.name);let score=n===q?100:n.startsWith(q)?80:hay.startsWith(q)?60:40;return{f,score}}).filter(Boolean).sort((a,b)=>b.score-a.score||a.f.name.localeCompare(b.f.name)).slice(0,10).map(x=>x.f)},[query,facilities]);"
new="useEffect(()=>{let active=true;const q=query.trim();if(!q){setSearchResults([]);return()=>{active=false}};const timer=setTimeout(async()=>{const safe=q.replace(/[,]/g,' ');const pattern=`%${safe}%`;const {data}=await supabase.from('facilities').select('*').or(`name.ilike.${pattern},address.ilike.${pattern},city.ilike.${pattern},state_code.ilike.${pattern},zip.ilike.${pattern}`).order('name').limit(10);if(active)setSearchResults(data||[])},220);return()=>{active=false;clearTimeout(timer)}},[query]);"
if old not in s: raise SystemExit('search block not found')
s=s.replace(old,new)
s=s.replace("const maxVisible=900","const maxVisible=500")
needle="function focus(f){setSelected(f);setSidebarOpen(false);if(mapRef.current&&Number.isFinite(+f.latitude)&&Number.isFinite(+f.longitude)){mapRef.current.flyTo([+f.latitude,+f.longitude],15,{duration:.55});setTimeout(()=>markers.current.get(f.id)?.openPopup(),600)}}"
repl=needle+"\n async function loadReviews(f){if(!f?.id){setReviews([]);return}const {data}=await supabase.from('facility_reviews').select('*').eq('facility_id',f.id).order('created_at',{ascending:false}).limit(20);setReviews(data||[])}\n async function submitReview(){if(!selected)return;if(!user){notify('Sign in to leave a review.');return}const {data,error}=await supabase.from('facility_reviews').insert({facility_id:selected.id,user_id:user.id,rating:reviewRating,notes:reviewNotes.trim()||null}).select().single();if(error){notify(error.message);return}setReviews(v=>[data,...v]);setReviewNotes('');notify('Review added.')}"
if needle not in s: raise SystemExit('focus block not found')
s=s.replace(needle,repl)
s=s.replace("useEffect(()=>{renderMarkers()},[facilities]);","useEffect(()=>{renderMarkers()},[facilities]);\n useEffect(()=>{loadReviews(selected)},[selected]);")
needle3="<hr/><div className=\"notes-title\"><b>Driver instructions</b></div><p>{selected.driver_instructions||'No driver notes have been added yet.'}</p>"
repl3="<hr/><div className=\"notes-title\"><b>Driver instructions</b></div><p>{selected.driver_instructions||'No driver notes have been added yet.'}</p><hr/><div className=\"notes-title\"><b>Driver reviews</b><span>{reviews.length} recent</span></div>{reviews.length?reviews.map(r=><div className=\"review-row\" key={r.id}><b>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</b><p>{r.notes||'No written note.'}</p></div>):<p>No reviews yet.</p>}{user&&<div className=\"review-form\"><label>Rating<select value={reviewRating} onChange={e=>setReviewRating(+e.target.value)}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></label><textarea rows=\"3\" value={reviewNotes} onChange={e=>setReviewNotes(e.target.value)} placeholder=\"How was the facility?\"/><button className=\"primary\" onClick={submitReview}>Add review</button></div>}"
if needle3 not in s: raise SystemExit('panel needle not found')
s=s.replace(needle3,repl3)
p.write_text(s)
